feat(gatsby-plugin-feed): warn for deprecations, validate options (#12085)
## Description

gatsby-plugin-feed tends to have slightly confusing behavior.

It's _too_ generalized, and for most non-trivial usages, consumers of the plugin will _want to_ implement custom feeds, queries, and serialize functions.

This PR introduces a few things, specifically:

- Validation of options (I've been bitten before by a missing output)
- Warnings of upcoming deprecations re: _not_ passing a custom feed, as well as not passing a custom serializer, both of which will be required in the next major bump of this plugin

Additionally, it fixes a bug, specifically that the _base_ query was deleted (no idea why?) which leads to an error with multiple feeds:

```shell
error Plugin gatsby-plugin-feed returned an error


  TypeError: Cannot read property 'siteMetadata' of undefined
  
  - internals.js:38 setup
    [rss-feed]/[gatsby-plugin-feed]/internals.js:38:40
```

I propose that we make this a minor version bump for this plugin, once merged.